CREATE TABLE submission_table1 (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    project_id INTEGER REFERENCES projects(id),
    submission_date TIMESTAMP DEFAULT NOW(),
    name TEXT,
    internetadresse TEXT,
    trag TEXT,
    zug TEXT,
    ansprechpartner TEXT,
    email TEXT,
    telefonnummer TEXT,
    oeffnungzeiten TEXT,
    versorgung TEXT,
    sonstiges_versorgung TEXT,
    laborbereiche TEXT,
    sonstiges_laborbereiche TEXT,
    leistungsspektrum TEXT,
    sonstiges_leistungsspektrum TEXT,
    ausstattung TEXT,
    hauptlieferanten TEXT,
    question_binary_1 TEXT,
    farbcodesystem TEXT,
    question_binary_2 TEXT,
    auftragsgenerierung TEXT,
    praeanalytik TEXT,
    befunduebermittlung TEXT,
    beratungsleistungen TEXT,
    question_binary_3 TEXT,
    organigramm_filename TEXT,
    ergaenzung TEXT
);